// {
//   1: {question: 'Are you responding successfully?', answers: {yes: {statusCode: 200}, no: {question: 2}}},
//   2: {question: 'Are you responding from a failure?', answers: {yes: {question: 3}, no: {statusCode: 100}}},
//   3: {question: 'Is that failure due to a server issue?', answers: {yes: {statusCode: 500}, no: {statusCode: 400}}}
// };

module.exports = {
  1: {question: 'Is the request a success?', answer: {yes: {question: 2}, no: {question: 17}}},
  2: {question: 'Should the user do some kind of redirect?', answer: {yes: {question: 3}, no: {question: 9}}},
  3: {question: 'Should the user redirect the request through a proxy?', answer: {yes: {statusCode: 305}, no: {question: 4}}},
  4: {question: 'Should the user choose between multiple URIs?', answer: {yes: {statusCode: 300}, no: {question: 5}}},
  5: {question: 'Is the redirect permanent?', answer: {yes: {question: 6}, no: {question: 7}}},
  6: {question: 'Do you allow to change the HTTP Method?', answer: {yes: {statusCode: 301}, no: {statusCode: 308}}},
  7: {question: 'Should the user use the new URI only this time?', answer: {yes: {statusCode: 307}, no: {question: 8}}},
  8: {question: 'The response is in another URI using GET?', answer: {yes: {statusCode: 303}, no: {statusCode: 302}}},
  9: {question: 'Did the user creates a new resource?', answer: {yes: {statusCode: 201}, no: {question: 10}}},
  10: {question: 'Do you want to let the user know the resource he is accessing has not been modified since last time?', answer: {yes: {statusCode: 304}, no: {question: 11}}},
  11: {question: 'Are you accepting the request, but still processing it?', answer: {yes: {statusCode: 202}, no: {question: 12}}},
  12: {question: 'Are you returning no content?', answer: {yes: {question: 13}, no: {question: 14}}},
  13: {question: 'Should the user reset the document view?', answer: {yes: {statusCode: 205}, no: {statusCode: 204}}},
  14: {question: 'Are you returning content from other source?', answer: {yes: {statusCode: 203}, no: {question: 15}}},
  15: {question: 'Are you returning partial content?', answer: {yes: {statusCode: 206}, no: {question: 16}}},
  16: {question: 'Do you want to notify the requester to wait?', answer: {yes: {statusCode: 100}, no: {statusCode: 200}}},
  17: {question: 'Is the error related to the request (user error)?', answer: {yes: {question: 18}, no: {question: 43}}},
  18: {question: 'Is the problem related with Authentication / Authorization?', answer: {yes: {question: 19}, no: {question: 21}}},
  19: {question: 'Does the user need to be authenticated through a proxy?', answer: {yes: {statusCode: 407}, no: {question: 20}}},
  20: {question: 'Is the user correctly Authenticated in your application?', answer: {yes: {statusCode: 403}, no: {statusCode: 401}}},
  21: {question: 'Is the user trying to access an unexacting resource?', answer: {yes: {statusCode: 404}, no: {question: 22}}},
  22: {question: 'Is the user trying to access a resource with an invalid method?', answer: {yes: {statusCode: 405}, no: {question: 23}}},
  23: {question: 'Is the user asking for a content type not possible to generate?', answer: {yes: {statusCode: 406}, no: {question: 24}}},
  24: {question: 'Is the user sending wrong content? (missing or wrong parameter)', answer: {yes: {statusCode: 422}, no: {question: 25}}},
  25: {question: 'Is the user sending a Media Type not recognized by the server?', answer: {yes: {statusCode: 415}, no: {question: 26}}},
  26: {question: 'Are some kind of precondition you\'re not able to met?', answer: {yes: {question: 27}, no: {question: 30}}},
  27: {question: 'Did the user send an Expect header you cannot fulfill?', answer: {yes: {statusCode: 417}, no: {question: 28}}},
  28: {question: 'Is the problem with a precondition in the request itself?', answer: {yes: {statusCode: 412}, no: {question: 29}}},
  29: {question: 'Is there a problem with a dependency with another request?', answer: {yes: {statusCode: 424}, no: {statusCode: 400}}},
  30: {question: 'Is the problem related with the length or amount of request?', answer: {yes: {question: 31}, no: {question: 36}}},
  31: {question: 'Do you need the user to send the Length header?', answer: {yes: {statusCode: 411}, no: {question: 32}}},
  32: {question: 'Is the URI too large?', answer: {yes: {statusCode: 414}, no: {question: 33}}},
  33: {question: 'Is the entity sent too large?', answer: {yes: {statusCode: 413}, no: {question: 34}}},
  34: {question: 'Is the Header too large?', answer: {yes: {statusCode: 431}, no: {question: 35}}},
  35: {question: 'Is the user sending too many request in a short period of time?', answer: {yes: {statusCode: 429}, no: {statusCode: 400}}},
  36: {question: 'Is there a problem with the resource the user is trying to access?', answer: {yes: {question: 37}, no: {question: 40}}},
  37: {question: 'Is the resource no longer available?', answer: {yes: {statusCode: 410}, no: {question: 38}}},
  38: {question: 'Is there some conflict (edit) with the resource? ', answer: {yes: {statusCode: 409}, no: {question: 39}}},
  39: {question: 'Is the resource Locked?', answer: {yes: {statusCode: 423}, no: {statusCode: 400}}},
  40: {question: 'Is the user asking for a portion of the file you cannot supply?', answer: {yes: {statusCode: 416}, no: {question: 41}}},
  41: {question: 'Do you need the user to upgrade to a different protocol?', answer: {yes: {statusCode: 426}, no: {question: 42}}},
  42: {question: 'Do you need the request to be conditional?', answer: {yes: {statusCode: 428}, no: {statusCode: 400}}},
  43: {question: 'Is there a problem processing the request?', answer: {yes: {question: 44}, no: {question: 53}}},
  44: {question: 'Is the request taking too long?', answer: {yes: {statusCode: 408}, no: {question: 45}}},
  45: {question: 'Do you Recognise the HTTP Method?', answer: {yes: {question: 46}, no: {statusCode: 501}}},
  46: {question: 'Do you support the HTTP Version?', answer: {yes: {question: 47}, no: {statusCode: 505}}},
  47: {question: 'As you acting as a gateway?', answer: {yes: {question: 48}, no: {question: 50}}},
  48: {question: 'Do you get a timeout from upstream?', answer: {yes: {statusCode: 504}, no: {question: 49}}},
  49: {question: 'Do you get an invalid response from upstream?', answer: {yes: {statusCode: 502}, no: {statusCode: 500}}},
  50: {question: 'Do you get inside an infinite loop processing the request?', answer: {yes: {question: 51}, no: {statusCode: 500}}},
  51: {question: 'Do you get inside an infinite loop negotiating the content?', answer: {yes: {statusCode: 506}, no: {question: 52}}},
  52: {question: 'Do you get inside an infinite loop processing the request?', answer: {yes: {statusCode: 508}, no: {statusCode: 500}}},
  53: {question: 'Did you run out of disk space to process the request?', answer: {yes: {statusCode: 507}, no: {question: 54}}},
  54: {question: 'Is your server down for maintenance of under a heavy load?', answer: {yes: {statusCode: 503}, no: {statusCode: 500}}}
};
